# Generated by Django 4.1 on 2023-10-15 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_attribute_object_attributevalue_attribute_and_more'),
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]

print('coreapp migration 2')
