# Generated by Django 4.1 on 2023-10-15 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, 
                                                    on_delete=django.db.models.deletion.CASCADE, 
                                                    parent_link=True, primary_key=True, serialize=False,
                                                    to='coreapp.basemodel')),
                ('title', models.CharField(max_length=100)),
            ],
            bases=('coreapp.basemodel',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, 
                                                    on_delete=django.db.models.deletion.CASCADE, 
                                                parent_link=True, primary_key=True, serialize=False, 
                                                to='coreapp.basemodel')),
                ('title', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, 
                                            to='product.category')),
            ],
            bases=('coreapp.basemodel',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, 
                                                    on_delete=django.db.models.deletion.CASCADE, 
                                                    parent_link=True, primary_key=True, serialize=False, 
                                                    to='coreapp.basemodel')),
                ('title', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('qty', models.BigIntegerField()),
                ('sku', models.CharField(max_length=100)),
                ('detail', models.TextField(max_length=5000)),
                ('category_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, 
                                                    related_name='products', to='product.category')),
            ],
            bases=('coreapp.basemodel',),
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, 
                                                    on_delete=django.db.models.deletion.CASCADE, 
                                                    parent_link=True, primary_key=True, serialize=False, 
                                                    to='coreapp.basemodel')),
                ('title', models.CharField(max_length=100)),
                ('attribute_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, 
                                                    related_name='attribute_values', to='product.attribute')),
            ],
            bases=('coreapp.basemodel',),
        ),
    ]
print('product migration 1')